name: Publish backend

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore backend/centraal-surfplatform-backend/centraal-surfplatform-backend.sln

      - name: Build
        run: dotnet build backend/centraal-surfplatform-backend/centraal-surfplatform-backend.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish backend/centraal-surfplatform-backend/centraal-surfplatform-backend.sln --configuration Release --no-build
